######################################################################
# Automatically generated by qmake (3.0) Mi. Dez. 10 16:49:19 2014
######################################################################

TEMPLATE = app
TARGET = hmgpp
INCLUDEPATH += .
QT += widgets gui core

# Input
SOURCES += hello.cpp
