######################################################################
# Automatically generated by qmake (3.0) Mi. Dez. 10 16:03:06 2014
######################################################################

TEMPLATE = app
TARGET = qt
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
